apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: servicebus-pubsub-secret
      key: connectionString
  - name: lockDurationInSec
    value: 300
  - name: handlerTimeoutInSec
    value: 300
  - name: maxConcurrentHandlers
    value: 50
  - name: maxActiveMessages
    value: 250
auth:
  secretStore: secretstore