apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redis-statestore-secret
      key: redisHost
  - name: redisPassword
    secretKeyRef:
      name: redis-statestore-secret
      key: redisPassword
  - name: keyPrefix
    value: none
auth:
  secretStore: secretstore